@startuml
class controller.MatchController {
- GetMatchesUseCase getMatchesUseCase
- GetMatchUseCase getMatchUseCase
+ ResponseEntity<GetAllMatchesResponse> getMatches()
+ ResponseEntity<MatchEntity> getMatch(Integer)
}


class controller.TicketController {
}
class controller.UserController {
- GetUsersUseCase getUsersUseCase
- GetUserUseCase getUserUseCase
- CreateUserUseCase createUserUseCase
- UpdateUserUseCase updateUserUseCase
- DeleteUserUseCase deleteUserUseCase
+ ResponseEntity<GetAllUsersResponse> getUsers()
+ ResponseEntity<UserEntity> getUser(Integer)
+ ResponseEntity<CreateUserResponse> createUser(CreateUserRequest)
+ ResponseEntity<Void> updateUser(Integer,UpdateUserRequest)
+ ResponseEntity<Void> deleteUser(Integer)
}


@enduml