variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  #GIT_DEPTH: "0"

stages:
  - build
  - test
  - deploy
  - sonarqube-check
#  - sonarqube-vulnerability-report

build:
  stage: build
  script:
    - ls
    - pwd
    - ./gradlew assemble
    - ./gradlew jar
    - docker build -t individual-back-end .

test:
  stage: test
  script:
    - ls
    - pwd
    - ./gradlew test

deploy:
  stage: deploy
  script:
    - ls
    - pwd
    - docker stop individual-back-end-staging
    - docker rm individual-back-end-staging
    - docker run -d -p 8090:8080 --net=individual_db_staging --env spring_profiles_active=staging --name=individual-back-end-staging individual-back-end

sonarqube-check:
  stage: sonarqube-check
  script:
    - ./gradlew test sonar jacocoTestReport

#sonarqube-vulnerability-report:
#  stage: sonarqube-vulnerability-report
#  script:
#    - 'curl -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL}/api/issues/gitlab_sast_export?projectKey=I499773_individual-back-end_69aca923-6ac3-4937-b9ea-7c2891568276&branch=${CI_COMMIT_BRANCH}&pullRequest=${CI_MERGE_REQUEST_IID}" -o gl-sast-sonar-report.json'
#  allow_failure: true
#  only:
#    - merge_requests
#    - master
#    - main
#    - develop
#  artifacts:
#    expire_in: 1 day
#    reports:
#      sast: gl-sast-sonar-report.json
#  dependencies:
#    - sonarqube-check