variables:
  SPRING_PROFILES_ACTIVE: test
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GITGUARDIAN_API_KEY: $GITGUARDIAN_API_KEY
  RAPID_API_KEY: $RAPID_API_KEY
  SPRING_DATASOURCE_URL: $SPRING_DATASOURCE_URL
  SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME
  SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradlew/wrapper
    - .gradle/caches

stages:
  - build
  - test
  - secret-detection
  - sonarqube-check
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble
    - ./gradlew jar
    - docker build -t individual-back-end .
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - echo "DB url: $env:$SPRING_DATASOURCE_URL"
    - echo "DB username: $env:SPRING_DATASOURCE_USERNAME"
    - echo "DB password: '$env:SPRING_DATASOURCE_PASSWORD"
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - build/reports/tests/

secret-detection:
  stage: secret-detection
  image: python:3.8
  script:
    - pip install ggshield
    - ggshield scan repo .
  only:
    - branches

sonarqube-check:
  stage: sonarqube-check
  script:
    - ./gradlew test jacocoTestReport sonar

deploy:
  stage: deploy
  script:
    - ls
    - pwd
    - docker stop individual-back-end-staging || true
    - docker rm individual-back-end-staging || true
    - docker run -d -p 8090:8080 --net=individual_db_staging --env spring_profiles_active=staging --name=individual-back-end-staging individual-back-end
  only:
    - master
  environment:
    name: staging